# Generated by Django 3.0.3 on 2020-02-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='level',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
