# Generated by Django 3.0.3 on 2020-02-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20200227_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='level',
            field=models.TextField(choices=[('Primary', 'Primary'), ('Preparatory', 'Preparatory'), ('Secondary', 'Secondary')], max_length=20),
        ),
    ]
