# Generated by Django 3.0.3 on 2020-02-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20200227_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Country',
            field=models.CharField(default='aaa', max_length=40),
        ),
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(default='aa', max_length=20),
        ),
    ]
