# Generated by Django 3.0.3 on 2020-02-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20200227_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='Country',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(max_length=20),
        ),
    ]
