# Generated by Django 3.0.3 on 2020-02-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_auto_20200227_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='level',
            new_name='stage',
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1),
        ),
    ]
